plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    signingConfigs {
        stable {
            storeFile file("../xauusd-stable.jks")
            storePassword "xauusd2026"
            keyAlias "xauusd"
            keyPassword "xauusd2026"
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = '17' }
    namespace 'com.xauusd.mobileengine'
    compileSdk 35
    buildTypes {
        debug { signingConfig signingConfigs.stable }
        release { signingConfig signingConfigs.stable; minifyEnabled false }
    }
    defaultConfig {
        applicationId 'com.xauusd.mobileengine'
        minSdk 26
        targetSdk 34
        versionCode 553
        versionName '5.2.10-FXOPEN'
    }
}

dependencies {
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'org.bouncycastle:bcprov-jdk18on:1.78.1'
}
